routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Models\QrCard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/update_password', [App\Http\Controllers\Auth\UpdatePasswordController::class, 'show'])
    ->name('update_password');
Route::post('/update_password', [App\Http\Controllers\Auth\UpdatePasswordController::class, 'updatePassword'])
    ->name('update_password_post');

Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'user/'], function() {
    Route::resource('settings', App\Http\Controllers\SettingsController::class)->only(['index', 'store']);
    Route::resource('qr', App\Http\Controllers\QrCardController::class)->only(['index', 'create', 'update', 'edit', 'destroy']);
    Route::get('qr/data', [App\Http\Controllers\QrCardController::class, 'data'])->name('qr.datatable');
    Route::get('qr/{qr}/pdf', [App\Http\Controllers\QrCardController::class, 'getPdf'])->name('qr.pdf');
    Route::resource('events', App\Http\Controllers\EventsController::class)->only(['index']);
    Route::get('events/data', [App\Http\Controllers\EventsController::class, 'data'])->name('events.datatable');
});

Route::get('/', [App\Http\Controllers\HomeController::class, 'home'])
    ->name('home');

Route::get('qr/{card_code}', [App\Http\Controllers\QrCardController::class, 'page'])
    ->name('qr.page');
Route::get('qr/{card_code}/file/{file_id}', [App\Http\Controllers\QrCardController::class, 'fileDownload'])
    ->name('qr.file');

resources/views/qr/create.blade.php
@extends('adminlte::page')

@section('title', __('QR Card Create'))

@section('content_header')
    <h1>{{ __('QR Card Create') }}</h1>
@stop

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('QR Card Create') }}</div>

                    <div class="card-body">
                        @if(session('success'))
                            <x-adminlte-alert theme="success" title="{{ __('Success') }}" dismissable>
                                {{ session('success') }}
                            </x-adminlte-alert>
                        @endif
                        <form action="{{ route('qr.store', $qr->id) }}" method="post" class="container">
                            @csrf
                            @method('PUT')
                            @include('qr.form')
                            <x-adminlte-button class="btn" type="submit" label="{{ __('Save') }}" theme="success"></x-adminlte-button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qr/edit.blade.php
@extends('adminlte::page')

@section('title', __('QR Card Edit'))

@section('content_header')
    <h1>{{ __('QR Card Edit') }}</h1>
@stop

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('QR Card Edit') }}</div>

                    <div class="card-body">
                        @if(session('success'))
                            <x-adminlte-alert theme="success" title="{{ __('Success') }}" dismissable>
                                {{ session('success') }}
                            </x-adminlte-alert>
                        @endif
                        @if(session('warning'))
                            <x-adminlte-alert theme="warning" title="{{ __('Warning') }}" dismissable>
                                {{ session('warning') }}
                            </x-adminlte-alert>
                        @endif
                        <form id="editForm" action="{{ route('qr.update', $qr->id) }}" method="post" enctype="multipart/form-data" class="container">
                            @csrf
                            @method('PUT')
                            @include('qr.form')
                            <x-adminlte-button type="button"
                                               label="{{ __('Show') }}"
                                               theme="primary"
                                               data-toggle="modal"
                                               data-target="#modalCardPreview"></x-adminlte-button>
                            <x-adminlte-button type="submit"
                                               label="{{ __('Save') }}"
                                               form="editForm"
                                               theme="success"></x-adminlte-button>
                            <x-adminlte-button type="button"
                                               label="{{ __('Delete') }}"
                                               form="deleteForm"
                                               theme="danger"
                                               data-toggle="modal"
                                               data-target="#modalDeleteConfirm"></x-adminlte-button>
                        </form>
                        <form id="deleteForm" action="{{ route('qr.destroy', $qr->id) }}" method="post">
                            @csrf
                            @method('DELETE')
                        </form>
                        <x-adminlte-modal id="modalDeleteConfirm" title="{{ __('Are you sure?') }}" theme="danger"
                                          icon="fas fa-question-circle">
                            {{ __('Are you sure you want to delete this QR?') }}
                            <x-slot name="footerSlot">
                                <x-adminlte-button theme="danger" label="{{ __('Delete') }}" type="submit" form="deleteForm"></x-adminlte-button>
                                <x-adminlte-button label="{{ __('Close') }}" data-dismiss="modal"></x-adminlte-button>
                            </x-slot>
                        </x-adminlte-modal>
                        <x-adminlte-modal id="modalCardPreview" title="{{ __('QR Card') }}" theme="default" size="lg">
                            <div class="d-flex flex-column align-items-center">
                                <div>{{ __('Here you can see your QR, short URL and download PDF') }}</div>
                                <div>
                                    <img src="{{ $qrImage ?? '' }}" alt="QR Code" />
                                </div>
                                <div>
                                    <a href="{{ route('qr.page', $qr->card_code, true) }}" target="_blank">{{ route('qr.page', $qr->card_code, true) }}
                                        <i class="fas fa-external-link-alt"></i>
                                    </a>
                                </div>
                                <div>
                                    <a class="btn btn-primary mt-2" href="{{ route('qr.pdf', $qr->id, true) }}" target="_blank">
                                        <i class="fa fa-download"></i> {{ $qr->title.'.pdf' }}
                                    </a>
                                </div>
                            </div>
                            <x-slot name="footerSlot">
                                <x-adminlte-button label="{{ __('Close') }}" data-dismiss="modal"></x-adminlte-button>
                            </x-slot>
                        </x-adminlte-modal>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qr/form.blade.php
@section('plugins.Summernote', true)
@section('plugins.BsCustomFileInput', true)
@section('plugins.BootstrapSwitch', true)
@section('plugins.JqueryUI', true)

<div class="row">
    <x-adminlte-input name="name"
                      label="{{ __('Name') }}"
                      fgroup-class="col-md-12"
                      value="{{ $qr->name }}"
                      enable-old-support>
        <x-slot name="bottomSlot">
            <span class="text-sm text-gray">
                {{ __('Internal name') }}
            </span>
        </x-slot>
    </x-adminlte-input>
</div>

<div class="row">
    <x-adminlte-input name="title"
                      label="{{ __('Title') }}"
                      fgroup-class="col-md-12"
                      value="{{ $qr->title }}"
                      enable-old-support>
        <x-slot name="bottomSlot">
            <span class="text-sm text-gray">
                {{ __('Title for the public page') }}
            </span>
        </x-slot>
    </x-adminlte-input>
</div>

<div class="row">
    <x-adminlte-input name="label"
                      label="{{ __('Event label') }}"
                      fgroup-class="col-md-12"
                      value="{{ $qr->label }}"
                      enable-old-support>
        <x-slot name="bottomSlot">
            <span class="text-sm text-gray">
                {{ __('To distinguish events by this field') }}
            </span>
        </x-slot>
    </x-adminlte-input>
</div>

<div class="row">
    <label class="col-md-12">{{ __('User settings') }}</label>
</div>

<div class="row ml-1 pl-2 border-left">
    <x-adminlte-input name="parameters__leading_text"
                      label="{{ __('Leading text') }}"
                      fgroup-class="col-md-9"
                      value="{{ $qr->parameters['leading_text'] ?? null }}"
                      enable-old-support readonly disabled>
        @if(($qr->parameters['leading_text'] ?? null) != ($qr->author->settings->parameters['leading_text'] ?? null))
            <x-slot name="bottomSlot">
                <span class="text-sm text-danger">
                    {{ __('Current and probably not relevant value') }}
                </span>
            </x-slot>
        @endif
    </x-adminlte-input>
    <x-adminlte-input-switch name="use_from_settings[leading_text]"
                             id="use_from_settings_leading_text"
                             label="{{ __('Update from settings') }}"
                             fgroup-class="col-md-3"
                             data-inverse="true"
                             enable-old-support>
    </x-adminlte-input-switch>

    <div class="col-md-9">
        <div class="container row d-flex flex-row align-items-center">
            <label>{{ __('Current logo:') }}</label>
            @if($qr->parameters['logo_url'] ?? [])
                <img class="ml-2" src="{{ asset($qr->parameters['logo_url']) }}" alt="Logo">
            @else
                <span class="ml-2 mb-2">{{ __('No logo') }}</span>
            @endif
        </div>
    </div>
    <x-adminlte-input-switch name="use_from_settings[logo_url]"
                             id="use_from_settings_logo_url"
                             label="{{ __('Update from settings') }}"
                             fgroup-class="col-md-3"
                             data-inverse="true"
                             enable-old-support>
    </x-adminlte-input-switch>
</div>

<div class="row">
    <label class="col-md-12">{{ __('Extra fields') }}</label>
</div>

<div class="row ml-1 pl-2 mb-2 border-left">
    @if (!$qr->fields && !$qr->author->settings->fields)
        <span class="ml-2 mb-2">{{ __('No extra fields added') }}</span>
    @else
        <ul id="sortable" class="col-6">
            @foreach($qr->fields as $field => $value)
                <x-adminlte-input name="parameters[fields][{{ $field }}]"
                                  label="{{ $field }}"
                                  value="{{ $value }}"
                                  enable-old-support>
                    <x-slot name="prependSlot">
                        <div class="input-group-text">
                            <i class="fas fa-user-cog"></i>
                        </div>
                    </x-slot>
                    <x-slot name="appendSlot">
                        <div class="input-group-text drag-n-drop">
                            <i class="fas fa-arrows-alt-v"></i>
                        </div>
                    </x-slot>
                    @if(!in_array($field, $qr->author->settings->fields))
                        <x-slot name="bottomSlot">
                            <span class="text-sm text-gray">
                                {{ __('Old field, leave empty to remove') }}
                            </span>
                        </x-slot>
                    @endif
                </x-adminlte-input>

            @endforeach
            @foreach($qr->author->settings->fields as $field)
                @if(!in_array($field, array_keys($qr->fields)))
                    <x-adminlte-input name="parameters[fields][{{ $field }}]"
                                      label="{{ $field }}"
                                      enable-old-support>
                        <x-slot name="prependSlot">
                            <div class="input-group-text">
                                <i class="fas fa-user-cog"></i>
                            </div>
                        </x-slot>
                        <x-slot name="appendSlot">
                            <div class="input-group-text drag-n-drop">
                                <i class="fas fa-arrows-alt-v"></i>
                            </div>
                        </x-slot>
                    </x-adminlte-input>
                @endif
            @endforeach
        </ul>
    @endif
</div>

<div class="row">
    <label class="col-md-12">{{ __('Files') }}</label>
</div>

<div class="row ml-1 pl-2 mb-2 border-left">
    @php
        if ($errors->has('file.*')) {
            $errors->add('file', $errors->first('file.*'));
        }
    @endphp
    <x-adminlte-input-file id="ifFile"
                           label="{{ __('Add files to the page') }}"
                           name="file[]"
                           fgroup-class="col-md-12"
                           placeholder="{{ __('Add files...') }}"
                           multiple>
        <x-slot name="bottomSlot">
            <span class="text-sm text-gray">
                {{
                    trans_choice(
                        'Max :max files, each file max :max_mb MB, multiple choice available',
                        App\Http\Requests\QrCardUpdateRequest::MAX_FILES_COUNT, [
                            'max' => App\Http\Requests\QrCardUpdateRequest::MAX_FILES_COUNT,
                            'max_mb' => App\Http\Requests\QrCardUpdateRequest::MAX_FILES_SIZE_MB,
                        ]
                    )
                }}
            </span>
        </x-slot>
    </x-adminlte-input-file>
    @forelse($qr->file_links ?? [] as $file)
        @php
            $isDeleted = in_array(intval($file['id']), array_values(old('delete_files') ?? []));
        @endphp
        <div class="col-md-12 d-inline-flex flex-row align-items-center mb-2">
            <span id="fileName_{{ $file['id'] }}" @class(['file_link_admin', 'text-muted' => $isDeleted])>{{ $file['name'] }}</span>
            <a @class(['btn', 'btn-sm', 'btn-primary', 'mx-2', 'text-nowrap', 'disabled' => $isDeleted])
               href="{{ $file['url'] }}"
               download="{{ $file['name'] }}"
               id="fileDownloadBtn_{{ $file['id'] }}"
               target="_blank">
                <i class="fa fa-download"></i> {{ __('Download') }}
            </a>
            <x-adminlte-button type="button"
                               label="{{ __('Delete') }}"
                               class="btn-sm text-nowrap"
                               theme="danger"
                               icon="fas fa-trash"
                               id="fileDeleteBtn_{{ $file['id'] }}"
                               data-toggle="modal"
                               data-target="#modalDeleteFileConfirm_{{ $file['id'] }}"
                               :disabled="$isDeleted"
            ></x-adminlte-button>
            <input type="hidden"
                   name="delete_files[]"
                   id="deleteFile_{{ $file['id'] }}"
                   @if($isDeleted) value="{{ $file['id'] }}" @endif>
            <x-adminlte-modal id="modalDeleteFileConfirm_{{ $file['id'] }}" title="{{ __('Are you sure?') }}" theme="danger"
                              icon="fas fa-question-circle">
                {{ __('Are you sure you want to delete file :filename?', ['filename' => $file['name']]) }}
                <x-slot name="footerSlot">
                    <x-adminlte-button theme="danger" label="{{ __('Delete') }}" type="submit" data-dismiss="modal"
                                       data-file="{{ $file['id'] }}"
                                       onclick="deleteFile($(this).data('file'))">
                    </x-adminlte-button>
                    <x-adminlte-button label="{{ __('Close') }}" data-dismiss="modal"></x-adminlte-button>
                </x-slot>
            </x-adminlte-modal>
        </div>
    @empty
        <div class="col-md-12 d-inline-flex flex-row align-items-center mb-2">{{ __('No files uploaded') }}</div>
    @endforelse
</div>

@php
    $config = [
        'height' => 500,
        'disableDragAndDrop' => true,
        'toolbar' => [
            // [groupName, [list of button]]
            ['insert', ['link']]
        ]
    ];
@endphp
<div class="row">
    <x-adminlte-textarea name="body"
                            label="{{ __('Content') }}"
                            fgroup-class="col-md-12"
                            rows="20"
                            enable-old-support>{!! $qr->body !!}</x-adminlte-textarea>
</div>

<div class="row">
    @php
        $config = [
            'state' => $qr->published,
            'inverse' => true
        ]
    @endphp
    <x-adminlte-input-switch name="published"
                             label="{{ __('Publish') }}"
                             fgroup-class="col-md-12"
                             igroup-size="sm"
                             :config="$config"
                             :checked="$qr->published"
                             enable-old-support
                             >
        <x-slot name="bottomSlot">
            <span class="text-sm text-gray">
                {{ __('Your card will be published when checked') }}
            </span>
        </x-slot>
    </x-adminlte-input-switch>
</div>

@section('js')
    <script type="text/javascript">
        function deleteFile(key) {
            $(`input#deleteFile_${key}`).val(key)
            $(`#fileName_${key}`).addClass('text-muted')
            $(`#fileDownloadBtn_${key}`).addClass('disabled')
            $(`#fileDeleteBtn_${key}`).attr('disabled', 'disabled')
        }

        $(document).ready(function () {
            $('#sortable').sortable()
        })
    </script>
@endsection

@section('css')
    <style type="text/css">
        .file_link_admin {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .drag-n-drop {
            cursor: grab;
        }
    </style>
@stop

resources/views/qr/index.blade.php
@extends('adminlte::page')

@section('title', __('Catalog'))

@section('content_header')
    <h1>{{ __('Catalog') }}</h1>
@stop

@section('plugins.Datatables', true)
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Your QR Cards') }}</div>

                    <div class="card-body">
                        @if(session('success'))
                            <x-adminlte-alert theme="success" title="{{ __('Success') }}" dismissable>
                                {{ session('success') }}
                            </x-adminlte-alert>
                        @endif
                        @if(session('warning'))
                            <x-adminlte-alert theme="warning" title="{{ __('Warning') }}" dismissable>
                                {{ session('warning') }}
                            </x-adminlte-alert>
                        @endif

                        @php
                            /** @var $cards */
                            $heads = [
                                ['label' => __('Name'), 'width' => 20],
                                __('Title'),
                                __('Created'),
                                ['label' => __('Is published'), 'width' => 5],
                                ['label' => __('Actions'), 'width' => 10],
                            ];
                            $config = [
                                'serverSide' => true,
                                'processing' => true,
                                'ajax' => route('qr.datatable'),
                                'ordering' => false,
                                'lengthChange' => false,
                                'searchDelay' => 600,
                                'dom' =>  '<"toolbar">frtip',
                                'language' => [
                                    'url' => asset('vendor/datatables-plugins/i18n/ru.json')
                                ]
                            ];
                        @endphp
                        <x-adminlte-datatable id="qr_table" :heads="$heads" :config="$config"></x-adminlte-datatable>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript">
        const btnEdit = id =>
            `<a href="qr/${id}/edit" class="btn btn-xs btn-default text-primary mx-1" title="{{ __('Edit') }}">
                <i class="fa fa-lg fa-fw fa-pen"></i>
            </a>`
        const iconPublished = '<i class="fa fa-lg fa-fw fa-check text-success"></i>'
        const iconUnpublished = '<i class="fa fa-lg fa-fw fa-times text-danger"></i>'
        const newBtn =
            `<a href="{{ route('qr.create') }}" class="btn btn-sm btn-primary">
                <i class="fa fa-fw fa-plus"></i>&nbsp;{{ __('New QR Card') }}
            </a>`

        $.extend(true, $.fn.dataTable.defaults, {
            'initComplete': () => {
                $("div.toolbar").css('float', 'left')
                $("div.toolbar").html(newBtn)
            },
            'columns': [
                {
                    'data': 'name'
                },
                {
                    'data': 'title'
                },
                {
                    'data': 'created_at',
                    render: function ( created_at, type, row ) {
                        let date = new Date(created_at)
                        return date.toLocaleDateString('ru-RU')
                    }
                },
                {
                    'data': 'published',
                    render: function ( published, type, row ) {
                        return published === true ? iconPublished : iconUnpublished;
                    }
                },
                {
                    'data': 'id',
                    render: function ( id, type, row ) {
                        return btnEdit(id)
                    }
                }
            ]
        });

        $(document).ready(function () {
            let dtable = $('#qr_table').dataTable().api()
            let searchWait = 0
            let searchWaitInterval
            $('.dataTables_filter input')
                .unbind() // Unbind previous default bindings
                .bind('input', function(e) {
                    let item = $(this)
                    searchWait = 0
                    if ($(item).val() === '') {
                        dtable.search('').draw()
                        return
                    }
                    if(!searchWaitInterval) searchWaitInterval = setInterval(function() {
                        if(searchWait >= 1) {
                            clearInterval(searchWaitInterval)
                            searchWaitInterval = ''
                            let searchTerm = $(item).val()
                            if (searchTerm.length >= 3) {
                                dtable.search(searchTerm).draw()
                            }
                            searchWait = 0
                        }
                        searchWait++
                    }, 300)
                })
                .bind('keydown', function(e) {
                    // If the user pressed ENTER, search
                    if (e.keyCode === 13) {
                        dtable.search(this.value).draw()
                    }
                });
        })
    </script>
@endsection

resources/views/qr/pdf.blade.php
<html>
<head>
    <title>{{ $qr->title }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 10px;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12pt;
            margin: 0;
        }

        table {
            table-layout: auto;
            width: 100%;
        }

        td {
            padding: 10px;
        }

        .qr_card {
            text-align: center;
            width: 100%;
        }

        .leading_text {
            font-size: 1.15em;
        }

        .qr {
            width: 250px;
        }

        .small {
            font-size: 0.85em;
        }

        .small .qr {
            width: 200px;
        }
    </style>
</head>
<body>
<table style="page-break-after: always;">
    @for ($j = 0; $j < 2; $j++)
        <col style="width:50%">
    @endfor
    @for ($i = 0; $i < 3; $i++)
        <tr>
            @for ($j = 0; $j < 2; $j++)
                <td>
                    <div class="qr_card">
                        @if ($qr->parameters['leading_text'] ?? null)
                            <div class="leading_text">{{ $qr->parameters['leading_text'] }}</div>
                        @endif
                        <img class="qr" src="{{ $qrImage }}">
                        @foreach($qr->fields as $key => $value)
                            <div class="field"><strong>{{ $key }}:</strong> {{ $value }}</div>
                        @endforeach
                    </div>
                </td>
            @endfor
        </tr>
    @endfor
</table>
<table class="small">
    @for ($j = 0; $j < 3; $j++)
        <col style="width:33.3%">
    @endfor
    @for ($i = 0; $i < 4; $i++)
        <tr>
            @for ($j = 0; $j < 3; $j++)
                <td>
                    <div class="qr_card">
                        @if ($qr->parameters['leading_text'] ?? null)
                            <div class="leading_text">{{ $qr->parameters['leading_text'] }}</div>
                        @endif
                        <img class="qr" src="{{ $qrImage }}">
                        @foreach($qr->fields as $key => $value)
                            <div class="field"><strong>{{ $key }}:</strong> {{ $value }}</div>
                        @endforeach
                    </div>
                </td>
            @endfor
        </tr>
    @endfor
</table>
</body>
</html>